### ISSUE TITLE
Dashboard is showing wrong sensor data when using Sense HAT

### ISSUE THREAD

**Issue by pckltr** [balenalabs/balena-sense#56]
I have a Sense HAT and the dashboard is showing data for air quality sensor, witch is not present, instead of showing data for the pressure sensor.

This is the default dashboard that was opened after installing Balena Sense.

Can I change something to show the correct sensor data?

![image](https://user-images.githubusercontent.com/18174048/73224125-2b319100-4171-11ea-9c54-ef9f734a3a47.png)

**Comment by chrisys** [comment]
@pckltr thanks for trying the project. The air quality reading is generated based on how 'good' the temperature and humidity values are; you can see that here: https://github.com/balenalabs/balena-sense/blob/master/sensor/scripts/sense_hat_air_quality.py#L32

The pressure sensor on the Sense-HAT is not currently supported.
