### ISSUE TITLE
Dockerfile for sensor app clones from `balena-io-playground`

### ISSUE THREAD

**Issue by xginn8** [balenalabs/balena-sense#94]
I think it'd be best to move that example project (https://github.com/balenalabs/balena-sense/blob/master/sensor/Dockerfile.aarch64#L9 and https://github.com/balenalabs/balena-sense/blob/master/sensor/Dockerfile.template#L9) to either `-examples` or `balenalabs`. cc @balenalabs/hardware-hackers

**Comment by chrisys** [comment]
Agreed @xginn8 - resolved in https://github.com/balenalabs/balena-sense/pull/95
